// DOM element references
export const elements = {
    settingsPanel: document.getElementById('settingsPanel'),
    toggleSettings: document.getElementById('toggleSettings'),
    overlay: document.getElementById('overlay'),
    chatView: document.getElementById('chatView'),
    galleryView: document.getElementById('galleryView'),
    chatContainer: document.getElementById('chatContainer'),
    messageInput: document.getElementById('messageInput'),
    sendBtn: document.getElementById('sendBtn'),
    typingIndicator: document.getElementById('typingIndicator'),
    typingAvatar: document.getElementById('typingAvatar'),
    imageIndicator: document.getElementById('imageIndicator'),
    connectionStatus: document.getElementById('connectionStatus'),
    openGalleryBtn: document.getElementById('openGalleryBtn'),
    backToChatBtn: document.getElementById('backToChatBtn'),
    galleryGrid: document.getElementById('galleryGrid'),
    galleryCharacterFilter: document.getElementById('galleryCharacterFilter'),
    galleryThumbnailCharacter: document.getElementById('galleryThumbnailCharacter'),
    galleryLightbox: document.getElementById('galleryLightbox'),
    lightboxImage: document.getElementById('lightboxImage'),
    closeLightboxBtn: document.getElementById('closeLightboxBtn'),
    currentCharacterName: document.getElementById('currentCharacterName'),
    welcomeAvatar: document.getElementById('welcomeAvatar'),
    welcomeMessage: document.getElementById('welcomeMessage'),

    // Settings inputs
    textProvider: document.getElementById('textProvider'),
    openrouterKey: document.getElementById('openrouterKey'),
    openrouterModel: document.getElementById('openrouterModel'),
    openrouterModelSearch: document.getElementById('openrouterModelSearch'),
    grokKey: document.getElementById('grokKey'),
    grokModel: document.getElementById('grokModel'),
    grokModelSearch: document.getElementById('grokModelSearch'),
    swarmUrl: document.getElementById('swarmUrl'),
    swarmModel: document.getElementById('swarmModel'),
    imageProvider: document.getElementById('imageProvider'),
    enableImageGeneration: document.getElementById('enableImageGeneration'),
    imgWidth: document.getElementById('imgWidth'),
    imgHeight: document.getElementById('imgHeight'),
    steps: document.getElementById('steps'),
    stepsValue: document.getElementById('stepsValue'),
    cfgScale: document.getElementById('cfgScale'),
    cfgValue: document.getElementById('cfgValue'),
    sampler: document.getElementById('sampler'),
    systemPrompt: document.getElementById('systemPrompt'),

    // Character elements
    charactersList: document.getElementById('charactersList'),
    addCharacterBtn: document.getElementById('addCharacterBtn'),
    characterModal: document.getElementById('characterModal'),
    closeModalBtn: document.getElementById('closeModalBtn'),
    cancelCharBtn: document.getElementById('cancelCharBtn'),
    saveCharBtn: document.getElementById('saveCharBtn'),
    modalTitle: document.getElementById('modalTitle'),
    charName: document.getElementById('charName'),
    charAvatar: document.getElementById('charAvatar'),
    charSystemPrompt: document.getElementById('charSystemPrompt'),
    charAppearance: document.getElementById('charAppearance'),
    charDescription: document.getElementById('charDescription'),
    charBackground: document.getElementById('charBackground'),
    charUserInfo: document.getElementById('charUserInfo'),
    thumbnailPreview: document.getElementById('thumbnailPreview'),
    generateThumbnailBtn: document.getElementById('generateThumbnailBtn'),
    generatePromptBtn: document.getElementById('generatePromptBtn'),

    // Buttons
    fetchModelsBtn: document.getElementById('fetchModelsBtn'),
    fetchOpenRouterModelsBtn: document.getElementById('fetchOpenRouterModelsBtn'),
    fetchGrokModelsBtn: document.getElementById('fetchGrokModelsBtn'),
    saveSettingsBtn: document.getElementById('saveSettingsBtn'),
    clearChatBtn: document.getElementById('clearChatBtn')
};
