// DOM element references
export const elements = {
    settingsPanel: document.getElementById('settingsPanel'),
    toggleSettings: document.getElementById('toggleSettings'),
    overlay: document.getElementById('overlay'),
    chatView: document.getElementById('chatView'),
    generatorView: document.getElementById('generatorView'),
    galleryView: document.getElementById('galleryView'),
    chatSettingsPane: document.getElementById('chatSettingsPane'),
    generatorSettingsPane: document.getElementById('generatorSettingsPane'),
    navChatBtn: document.getElementById('navChatBtn'),
    navGeneratorBtn: document.getElementById('navGeneratorBtn'),
    navGalleryBtn: document.getElementById('navGalleryBtn'),
    currentViewDescription: document.getElementById('currentViewDescription'),
    chatContainer: document.getElementById('chatContainer'),
    messageInput: document.getElementById('messageInput'),
    sendBtn: document.getElementById('sendBtn'),
    typingIndicator: document.getElementById('typingIndicator'),
    typingAvatar: document.getElementById('typingAvatar'),
    imageIndicator: document.getElementById('imageIndicator'),
    connectionStatus: document.getElementById('connectionStatus'),
    logoutBtn: document.getElementById('logoutBtn'),
    galleryGrid: document.getElementById('galleryGrid'),
    gallerySourceFilter: document.getElementById('gallerySourceFilter'),
    galleryCharacterFilter: document.getElementById('galleryCharacterFilter'),
    galleryThumbnailCharacter: document.getElementById('galleryThumbnailCharacter'),
    galleryLightbox: document.getElementById('galleryLightbox'),
    lightboxImage: document.getElementById('lightboxImage'),
    lightboxVideo: document.getElementById('lightboxVideo'),
    closeLightboxBtn: document.getElementById('closeLightboxBtn'),
    currentCharacterDisplay: document.getElementById('currentCharacterDisplay'),
    currentCharacterName: document.getElementById('currentCharacterName'),
    currentUsername: document.getElementById('currentUsername'),
    currentCredits: document.getElementById('currentCredits'),
    adminPanel: document.getElementById('adminPanel'),
    adminUsersStatus: document.getElementById('adminUsersStatus'),
    adminUsersList: document.getElementById('adminUsersList'),
    welcomeAvatar: document.getElementById('welcomeAvatar'),
    welcomeMessage: document.getElementById('welcomeMessage'),

    // Settings inputs
    textProvider: document.getElementById('textProvider'),
    openrouterKey: document.getElementById('openrouterKey'),
    openrouterModel: document.getElementById('openrouterModel'),
    openrouterModelSearch: document.getElementById('openrouterModelSearch'),
    swarmUrl: document.getElementById('swarmUrl'),
    swarmModel: document.getElementById('swarmModel'),
    comfyUrl: document.getElementById('comfyUrl'),
    comfyModel: document.getElementById('comfyModel'),
    imageProvider: document.getElementById('imageProvider'),
    enableImageGeneration: document.getElementById('enableImageGeneration'),
    imgWidth: document.getElementById('imgWidth'),
    imgHeight: document.getElementById('imgHeight'),
    steps: document.getElementById('steps'),
    stepsValue: document.getElementById('stepsValue'),
    cfgScale: document.getElementById('cfgScale'),
    cfgValue: document.getElementById('cfgValue'),
    sampler: document.getElementById('sampler'),
    systemPrompt: document.getElementById('systemPrompt'),

    // Character elements
    charactersList: document.getElementById('charactersList'),
    addCharacterBtn: document.getElementById('addCharacterBtn'),
    characterModal: document.getElementById('characterModal'),
    closeModalBtn: document.getElementById('closeModalBtn'),
    cancelCharBtn: document.getElementById('cancelCharBtn'),
    saveCharBtn: document.getElementById('saveCharBtn'),
    modalTitle: document.getElementById('modalTitle'),
    charName: document.getElementById('charName'),
    charAvatar: document.getElementById('charAvatar'),
    charSystemPrompt: document.getElementById('charSystemPrompt'),
    charAppearance: document.getElementById('charAppearance'),
    charDescription: document.getElementById('charDescription'),
    charBackground: document.getElementById('charBackground'),
    charUserInfo: document.getElementById('charUserInfo'),
    thumbnailPreview: document.getElementById('thumbnailPreview'),
    generateThumbnailBtn: document.getElementById('generateThumbnailBtn'),
    generatePromptBtn: document.getElementById('generatePromptBtn'),

    // Buttons
    fetchModelsBtn: document.getElementById('fetchModelsBtn'),
    fetchComfyModelsBtn: document.getElementById('fetchComfyModelsBtn'),
    fetchOpenRouterModelsBtn: document.getElementById('fetchOpenRouterModelsBtn'),
    refreshUsersBtn: document.getElementById('refreshUsersBtn'),
    saveSettingsBtn: document.getElementById('saveSettingsBtn'),
    clearChatBtn: document.getElementById('clearChatBtn')
};
